{
  "comments": [
    {
      "key": {
        "uuid": "7a95b574_2c6a382b",
        "filename": "appengine/findit/handlers/build_failure.py",
        "patchSetId": 1
      },
      "lineNbr": 414,
      "author": {
        "id": 1002882
      },
      "writtenOn": "2017-05-31T16:42:54Z",
      "side": 1,
      "message": "to be updated.",
      "range": {
        "startLine": 414,
        "startChar": 7,
        "endLine": 414,
        "endChar": 24
      },
      "revId": "5992fb707428d58601969fa6fc0b9282df79f923",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    }
  ]
}