{
  "comments": [
    {
      "key": {
        "uuid": "76f4be1f_7d745cc6",
        "filename": "/COMMIT_MSG",
        "patchSetId": 4
      },
      "lineNbr": 18,
      "author": {
        "id": 1178184
      },
      "writtenOn": "2018-02-07T21:13:33Z",
      "side": 1,
      "message": "nit: remove empty line",
      "revId": "cf0a3692aa497c4037baf906f0237c7ddac95b87",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "71be265a_7c20ae5e",
        "filename": "/COMMIT_MSG",
        "patchSetId": 4
      },
      "lineNbr": 18,
      "author": {
        "id": 1119424
      },
      "writtenOn": "2018-02-07T22:57:19Z",
      "side": 1,
      "message": "Done",
      "parentUuid": "76f4be1f_7d745cc6",
      "revId": "cf0a3692aa497c4037baf906f0237c7ddac95b87",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "7b918332_6a1cee58",
        "filename": "appengine/findit/model/flake/master_flake_analysis.py",
        "patchSetId": 4
      },
      "lineNbr": 24,
      "author": {
        "id": 1178184
      },
      "writtenOn": "2018-02-07T21:13:33Z",
      "side": 1,
      "message": "Do you have plans to translate between master/builder/build_number --\u003e bbucket_id when this happens?",
      "range": {
        "startLine": 24,
        "startChar": 2,
        "endLine": 24,
        "endChar": 67
      },
      "revId": "cf0a3692aa497c4037baf906f0237c7ddac95b87",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "c697588f_cc104104",
        "filename": "appengine/findit/model/flake/master_flake_analysis.py",
        "patchSetId": 4
      },
      "lineNbr": 24,
      "author": {
        "id": 1119424
      },
      "writtenOn": "2018-02-07T22:57:19Z",
      "side": 1,
      "message": "No, I don\u0027t think that\u0027s related to the changes here, what I\u0027m referring to here is cleaning up data points. If translation is needed that should be a function in build_util.py",
      "parentUuid": "7b918332_6a1cee58",
      "range": {
        "startLine": 24,
        "startChar": 2,
        "endLine": 24,
        "endChar": 67
      },
      "revId": "cf0a3692aa497c4037baf906f0237c7ddac95b87",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "23a24e65_a1fd404d",
        "filename": "appengine/findit/model/flake/master_flake_analysis.py",
        "patchSetId": 4
      },
      "lineNbr": 24,
      "author": {
        "id": 1178184
      },
      "writtenOn": "2018-02-08T02:28:14Z",
      "side": 1,
      "message": "I\u0027m asking when this change actually goes live, will you do that data migration?",
      "parentUuid": "c697588f_cc104104",
      "range": {
        "startLine": 24,
        "startChar": 2,
        "endLine": 24,
        "endChar": 67
      },
      "revId": "cf0a3692aa497c4037baf906f0237c7ddac95b87",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "d55f4403_e085a925",
        "filename": "appengine/findit/model/flake/master_flake_analysis.py",
        "patchSetId": 4
      },
      "lineNbr": 24,
      "author": {
        "id": 1119424
      },
      "writtenOn": "2018-02-08T06:37:12Z",
      "side": 1,
      "message": "I don\u0027t think it\u0027s necessary at this stage, as build_number is display only and doesn\u0027t need to be converted once build_id is in place since it doesn\u0027t map to a new build id. I also don\u0027t know once the switch to build ids is made if old links to buildbucket builds would even still work?",
      "parentUuid": "23a24e65_a1fd404d",
      "range": {
        "startLine": 24,
        "startChar": 2,
        "endLine": 24,
        "endChar": 67
      },
      "revId": "cf0a3692aa497c4037baf906f0237c7ddac95b87",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "b1d4f419_6b30f0c3",
        "filename": "appengine/findit/pipelines/flake_failure/determine_approximate_pass_rate_pipeline.py",
        "patchSetId": 4
      },
      "lineNbr": 45,
      "author": {
        "id": 1178184
      },
      "writtenOn": "2018-02-07T21:13:33Z",
      "side": 1,
      "message": "Does this need to be a pipeline? Makes more sense as just a call.\n\nAlso if it does, mind moving to it\u0027s own file?",
      "range": {
        "startLine": 22,
        "startChar": 0,
        "endLine": 45,
        "endChar": 0
      },
      "revId": "cf0a3692aa497c4037baf906f0237c7ddac95b87",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "d7e42b39_8b416b58",
        "filename": "appengine/findit/pipelines/flake_failure/determine_approximate_pass_rate_pipeline.py",
        "patchSetId": 4
      },
      "lineNbr": 45,
      "author": {
        "id": 1119424
      },
      "writtenOn": "2018-02-07T22:57:19Z",
      "side": 1,
      "message": "Unfortunately this has to be in a pipeline, based on where it\u0027s being called the actual information that goes into a data point is yielded from a GeneratorPipeline so\n\nswarming_task_output \u003d yield RunFlakeSwarmingTaskPipeline(...)\ndata_point_util.UpdateAnalysisDataPoints(swarming_task_output)\n\ndoesn\u0027t work as-is, it has to be wrapped in\n\nswarming_task_output \u003d yield RunFlakeSwarmingTaskPipeline()\nyield UpdateFlakeAnalysisDataPointsPipeline()",
      "parentUuid": "b1d4f419_6b30f0c3",
      "range": {
        "startLine": 22,
        "startChar": 0,
        "endLine": 45,
        "endChar": 0
      },
      "revId": "cf0a3692aa497c4037baf906f0237c7ddac95b87",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "958a41a8_6d61e6f5",
        "filename": "appengine/findit/pipelines/flake_failure/run_flake_swarming_task_pipeline.py",
        "patchSetId": 4
      },
      "lineNbr": 54,
      "author": {
        "id": 1178184
      },
      "writtenOn": "2018-02-07T21:13:33Z",
      "side": 1,
      "message": "I think moving forward, we should commit to setting start/end times for everything. Even in case of error, these values can still be populated.",
      "range": {
        "startLine": 50,
        "startChar": 2,
        "endLine": 54,
        "endChar": 73
      },
      "revId": "cf0a3692aa497c4037baf906f0237c7ddac95b87",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "5b86cce4_033f2f57",
        "filename": "appengine/findit/pipelines/flake_failure/run_flake_swarming_task_pipeline.py",
        "patchSetId": 4
      },
      "lineNbr": 54,
      "author": {
        "id": 1119424
      },
      "writtenOn": "2018-02-07T22:57:19Z",
      "side": 1,
      "message": "That\u0027s a good idea however I think requires some more thought, it\u0027s possible for a task to fail outright without ever being triggered, e.g. no task id. in that case started time and completed times aren\u0027t from the swarming tasks themselves, but would then have to be populted by Findit. This will then throw off the calculations for how many tasks can run, so for now I think it\u0027s better we discard the results that had error altogether. There\u0027s already a TODO (marked in several appropriate places) that some task data can still be salvaged, but this is a whole different can of worms and should be addressed when the time comes should we even choose to go that route.",
      "parentUuid": "958a41a8_6d61e6f5",
      "range": {
        "startLine": 50,
        "startChar": 2,
        "endLine": 54,
        "endChar": 73
      },
      "revId": "cf0a3692aa497c4037baf906f0237c7ddac95b87",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "032d5f2a_95756f46",
        "filename": "appengine/findit/pipelines/flake_failure/run_flake_swarming_task_pipeline.py",
        "patchSetId": 4
      },
      "lineNbr": 54,
      "author": {
        "id": 1178184
      },
      "writtenOn": "2018-02-08T02:28:14Z",
      "side": 1,
      "message": "end_time can be set on our end in the case of error? Might throw off the calculation a bit, but in the correct direction (worst-case our calculation is over). In the case where this happens, it\u0027s not a big deal since the swarming task will return on completion.",
      "parentUuid": "5b86cce4_033f2f57",
      "range": {
        "startLine": 50,
        "startChar": 2,
        "endLine": 54,
        "endChar": 73
      },
      "revId": "cf0a3692aa497c4037baf906f0237c7ddac95b87",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "159ad818_d122135e",
        "filename": "appengine/findit/pipelines/flake_failure/run_flake_swarming_task_pipeline.py",
        "patchSetId": 4
      },
      "lineNbr": 54,
      "author": {
        "id": 1119424
      },
      "writtenOn": "2018-02-08T06:37:12Z",
      "side": 1,
      "message": "In this context I don\u0027t think it\u0027s possible have started_time but not ended_time and vice versa. By the time this RunFlakeSwarmingTaskOutput is created, swarming has already done it\u0027s part and returned to us everything in the callback when the task completes, which includes both started_time and completed_time in the json response. They are not supposed to be managed by Findit. If there were problems even getting the response from swarming, this object would never even be created.\n\nThe check for started_time and end_time both being populated is more of a defensive check, if the code made it here I don\u0027t know of a way for them not to both be populated unless there\u0027s a bug in swarming or they change the response structure on us.\n\nIn general if something\u0027s missing here there\u0027s a chance other things have gone quite wrong as well and we shouldn\u0027t try too hard to self-repair as that may lead to other false signals later down the line too, bailing out with retry as we already have seems the safer way to go.",
      "parentUuid": "032d5f2a_95756f46",
      "range": {
        "startLine": 50,
        "startChar": 2,
        "endLine": 54,
        "endChar": 73
      },
      "revId": "cf0a3692aa497c4037baf906f0237c7ddac95b87",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "ddf726a6_4b8cb3d1",
        "filename": "appengine/findit/services/flake_failure/pass_rate_util.py",
        "patchSetId": 4
      },
      "lineNbr": 27,
      "author": {
        "id": 1178184
      },
      "writtenOn": "2018-02-07T21:13:33Z",
      "side": 1,
      "message": "nit: split these into variables so this code is readable.",
      "range": {
        "startLine": 25,
        "startChar": 8,
        "endLine": 27,
        "endChar": 61
      },
      "revId": "cf0a3692aa497c4037baf906f0237c7ddac95b87",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "91e54d9a_ba0690d0",
        "filename": "appengine/findit/services/flake_failure/pass_rate_util.py",
        "patchSetId": 4
      },
      "lineNbr": 27,
      "author": {
        "id": 1119424
      },
      "writtenOn": "2018-02-07T22:57:19Z",
      "side": 1,
      "message": "Done",
      "parentUuid": "ddf726a6_4b8cb3d1",
      "range": {
        "startLine": 25,
        "startChar": 8,
        "endLine": 27,
        "endChar": 61
      },
      "revId": "cf0a3692aa497c4037baf906f0237c7ddac95b87",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": false
    }
  ]
}